### ISSUE TITLE
PHP Fatal error:  Class 'Mage_Codebaseexceptions_Helper_Data' not found

### ISSUE THREAD

**Issue by yattias** [airbrake/Airbrake-Magento#11]
Hi,

First, thanks for creating this extension.

The route ``/exceptions/index/test`` works fine and reports to Airbrake but it appears that the extension fails to report other errors. My error log is filled with:

``PHP Fatal error:  Class 'Mage_Codebaseexceptions_Helper_Data' not found``

This above class is nowhere to be found.

Do you have any insight?

**Comment by kyrylo** [comment]
Thanks for the error report. Do you know how to reproduce this, so I could take a closer look?

**Comment by yattias** [comment]
Sorry but I don't. I just noticed our error log being filled with these. I think that: ``Mage_Codebaseexceptions_Helper_Data`` should be ``Elgentos_Codebaseexceptions_Helper_Data``. You can take a look [here](https://github.com/elgentos/CodebaseExceptions/blob/master/app/code/community/Elgentos/CodebaseExceptions/Helper/Data.php).

**Comment by kyrylo** [comment]
From what I see it already is `Elgentos_Codebaseexceptions_Helper_Data`. Please ping us if you know how to reproduce this. Otherwise, it's pretty much impossible to fix it. :confused:
