### ISSUE TITLE
Notice is thrown when using Airbrake in CLI mode

### ISSUE THREAD

**Issue by tmotyl** [airbrake/Airbrake-Magento#9]
I found out that this plugin doesn't work (throws a notice when running in the cli mode).
It's because it assumes some globals are always present like $_SERVER['REQUEST_URI']
see
https://github.com/airbrake/Airbrake-Magento/blob/master/app/code/community/Elgentos/CodebaseExceptions/Helper/Data.php#L14

**Comment by kyrylo** [comment]
Could you please show an example of such a notice? Feel free to connect with us via our support chat to share it if the URL is private.

**Comment by tmotyl** [comment]
no problem:

```
PHP Notice:  Undefined index: REQUEST_URI in app/code/community/Elgentos/CodebaseExceptions/Helper/Data.php on line 14
PHP Stack trace:
PHP   1. {main}() shell/log.php:0
PHP   2. Mage_Shell_Log->run() shell/log.php:196
PHP   3. Mage::logException() shell/log.php:105
PHP   4. Mage::log() app/Mage.php:860
PHP   5. Zend_Log->log() app/Mage.php:843
PHP   6. Zend_Log_Writer_Abstract->write() lib/Zend/Log.php:438
PHP   7. Elgentos_CodebaseExceptions_Model_Log_Writer_Stream->_write() lib/Zend/Log/Writer/Abstract.php:85
PHP   8. Mage::helper() app/code/community/Elgentos/CodebaseExceptions/Model/Log/Writer/Stream.php:17
PHP   9. Elgentos_CodebaseExceptions_Helper_Data->__construct() app/Mage.php:548
PHP  10. mageCoreErrorHandler() app/Mage.php:14
PHP  11. Mage::log() app/code/core/Mage/Core/functions.php:247
PHP  12. Zend_Log->log() app/Mage.php:843
PHP  13. Zend_Log_Writer_Abstract->write() lib/Zend/Log.php:438
PHP  14. Elgentos_CodebaseExceptions_Model_Log_Writer_Stream->_write() lib/Zend/Log/Writer/Abstract.php:85
PHP  15. Mage::helper() app/code/community/Elgentos/CodebaseExceptions/Model/Log/Writer/Stream.php:17
PHP  16. Elgentos_CodebaseExceptions_Helper_Data->__construct() app/Mage.php:548
```

how to reproduce,
edit shell/log.php and add testing code at the beginning of run method:

```
   public function run()
    {
try {
    Mage::throwException("test");
} catch(Exception $e) {
    Mage::logException($e);
}
```

run the script with
shell > php log.php


(I;m assuming you have the pull request https://github.com/airbrake/Airbrake-Magento/pull/4 in)

**Comment by kyrylo** [comment]
Thanks for the information, I can see the problem. Since the problem is obvious, I assume the fix should be trivial. Would you be interested in submitting a PR? I am very excited about your work on this repo :)
